# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  #configurando a imagem que deseja utilizar
  config.vm.box = "centos/7"
  #realizando o forwarded para a porta 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  #VagrantFile vai procurar um provision com o nome de provision.sh
  config.vm.provision "shell", path: "provision.sh"
  
end
